# Generated by Django 5.1.3 on 2024-11-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='picure',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
    ]
